{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:27:08+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:27:10+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:49+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:50+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:55+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:55+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:56+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:57+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:59+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:38:59+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:39:21+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:39:21+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:39:33+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T10:39:34+07:00"}
{"level":"error","msg":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","res":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T10:40:43+07:00"}
{"err":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"gmfhdgf","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":292,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T10:40:43+07:00"}
{"level":"error","msg":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","res":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T10:41:19+07:00"}
{"err":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"gmfhdgf\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"gmfhdgf","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":292,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T10:41:19+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T11:36:31+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T11:36:32+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T11:36:38+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T11:36:39+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:19:07+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:19:08+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:31:49+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:31:49+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:41:25+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:41:25+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:41:26+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.69.163\", user \"postgres\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:41:26+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:52:16+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:52:20+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:52:54+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:52:59+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:53:07+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:53:16+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:53:59+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-09T13:54:04+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T13:57:10+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":292,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T13:57:10+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T14:10:18+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":292,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T14:10:18+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T14:11:01+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":292,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T14:11:01+07:00"}
{"level":"error","msg":"Get \"htttps://google.com\": unsupported protocol scheme \"htttps\"","res":"Get \"htttps://google.com\": unsupported protocol scheme \"htttps\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T14:11:27+07:00"}
{"err":"Get \"htttps://google.com\": unsupported protocol scheme \"htttps\"","level":"error","msg":"Get \"htttps://google.com\": unsupported protocol scheme \"htttps\"","req":{"Header":{},"Body":{},"Url":"htttps://google.com","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":292,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T14:11:27+07:00"}
{"level":"error","msg":"Get \"khjbmn%20v%20\": unsupported protocol scheme \"\"","res":"Get \"khjbmn%20v%20\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T14:42:37+07:00"}
{"err":"Get \"khjbmn%20v%20\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"khjbmn%20v%20\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"khjbmn v ","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":292,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T14:42:37+07:00"}
{"level":"error","msg":"Get \"nmbb\": unsupported protocol scheme \"\"","res":"Get \"nmbb\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T14:52:42+07:00"}
{"err":"Get \"nmbb\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"nmbb\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"nmbb","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":293,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T14:52:42+07:00"}
{"level":"error","msg":"Get \"nmbb\": unsupported protocol scheme \"\"","res":"Get \"nmbb\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T14:53:32+07:00"}
{"err":"Get \"nmbb\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"nmbb\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"nmbb","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":293,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T14:53:32+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T14:54:34+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":293,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T14:54:34+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:00:06+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":293,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:00:06+07:00"}
{"level":"error","msg":"Get \"https://localhost?aas\": dial tcp [::1]:443: connectex: No connection could be made because the target machine actively refused it.","res":"Get \"https://localhost?aas\": dial tcp [::1]:443: connectex: No connection could be made because the target machine actively refused it.","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:00:26+07:00"}
{"err":"Get \"https://localhost?aas\": dial tcp [::1]:443: connectex: No connection could be made because the target machine actively refused it.","level":"error","msg":"Get \"https://localhost?aas\": dial tcp [::1]:443: connectex: No connection could be made because the target machine actively refused it.","req":{"Header":{},"Body":{},"Url":"https://localhost?aas","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":293,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:00:26+07:00"}
{"level":"error","msg":"Get \"https://localhost:3000\": dial tcp [::1]:3000: connectex: No connection could be made because the target machine actively refused it.","res":"Get \"https://localhost:3000\": dial tcp [::1]:3000: connectex: No connection could be made because the target machine actively refused it.","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:01:37+07:00"}
{"err":"Get \"https://localhost:3000\": dial tcp [::1]:3000: connectex: No connection could be made because the target machine actively refused it.","level":"error","msg":"Get \"https://localhost:3000\": dial tcp [::1]:3000: connectex: No connection could be made because the target machine actively refused it.","req":{"Header":{},"Body":{},"Url":"https://localhost:3000","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":293,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:01:37+07:00"}
{"level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","res":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:47:24+07:00"}
{"err":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"czcZxcassc","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:47:24+07:00"}
{"level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","res":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:48:41+07:00"}
{"err":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"czcZxcassc","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:48:41+07:00"}
{"level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","res":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:48:57+07:00"}
{"err":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"czcZxcassc","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:48:57+07:00"}
{"level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","res":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:54:27+07:00"}
{"err":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"czcZxcassc\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"czcZxcassc","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:54:27+07:00"}
{"level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","res":"Get \"123\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:55:11+07:00"}
{"err":"Get \"123\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"123","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:55:11+07:00"}
{"level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","res":"Get \"123\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:56:19+07:00"}
{"err":"Get \"123\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"123","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:56:19+07:00"}
{"level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","res":"Get \"123\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:57:34+07:00"}
{"err":"Get \"123\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"123","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:57:34+07:00"}
{"level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","res":"Get \"123\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T15:58:32+07:00"}
{"err":"Get \"123\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"123","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T15:58:33+07:00"}
{"level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","res":"Get \"123\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-09T16:15:18+07:00"}
{"err":"Get \"123\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"123\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"123","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":301,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-09T16:15:18+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-10T14:34:18+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":301,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-10T14:34:18+07:00"}
{"level":"error","msg":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","res":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-11T10:43:28+07:00"}
{"err":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error","msg":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","req":{"Header":{},"Body":{},"Url":"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":301,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-11T10:43:28+07:00"}
{"level":"error","msg":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","res":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-11T10:43:40+07:00"}
{"err":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error","msg":"Get \"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50\": dial tcp 103.53.89.24:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","req":{"Header":{},"Body":{},"Url":"https://crmconnect.misa.vn/api/v1/Employees?page=1\u0026pageSize=50","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":301,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-11T10:43:40+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T11:11:43+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-11T17:10:43+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":301,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-11T17:10:43+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-11T17:11:42+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":301,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-11T17:11:42+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-11T18:22:38+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":301,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-11T18:22:38+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:06+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:06+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:06+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:16+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:16+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:21+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:21+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:21+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:21+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:22+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:22+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:22+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:22+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:43+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:43+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:26:43+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:28:27+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:28:27+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:28:27+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:37:18+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:37:18+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:37:18+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:37:55+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-11T18:37:55+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:15:12+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:15:12+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:16:43+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:16:43+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:20:20+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:20:37+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:20:48+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T00:20:48+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:40:42+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:40:42+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:48:55+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:48:55+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:49:08+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:49:08+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:49:09+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:52:46+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:53:02+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:57:50+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:57:50+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:57:51+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:58:17+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:58:19+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:58:19+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:58:30+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:58:32+07:00"}
{"level":"error","msg":"pq: the database system is in recovery mode","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T08:58:32+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:07:16+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:07:48+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:07:58+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:08:30+07:00"}
{"level":"error","msg":"pq: the database system is starting up","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:18:46+07:00"}
{"level":"error","msg":"pq: the database system is starting up","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:18:46+07:00"}
{"level":"error","msg":"pq: the database system is starting up","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:18:46+07:00"}
{"level":"error","msg":"pq: the database system is starting up","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:18:50+07:00"}
{"level":"error","msg":"pq: the database system is starting up","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-14T09:18:50+07:00"}
{"level":"error","msg":"Get \"vsds\": unsupported protocol scheme \"\"","res":"Get \"vsds\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-15T18:11:22+07:00"}
{"err":"Get \"vsds\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"vsds\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"vsds","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-15T18:11:22+07:00"}
{"level":"error","msg":"Get \"sas\": unsupported protocol scheme \"\"","res":"Get \"sas\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-15T18:22:59+07:00"}
{"err":"Get \"sas\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"sas\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"sas","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":295,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-15T18:22:59+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-16T09:12:20+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-16T09:12:20+07:00"}
{"level":"error","msg":"Get \"https;//%C3%A1%C4%91%C3%A2sdq%C6%B0d\": unsupported protocol scheme \"\"","res":"Get \"https;//%C3%A1%C4%91%C3%A2sdq%C6%B0d\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-17T09:02:13+07:00"}
{"err":"Get \"https;//%C3%A1%C4%91%C3%A2sdq%C6%B0d\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"https;//%C3%A1%C4%91%C3%A2sdq%C6%B0d\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"https;//áđâsdqưd","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-17T09:02:13+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-17T09:05:29+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-17T09:05:29+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-17T09:36:57+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-17T09:36:57+07:00"}
{"level":"error","msg":"Get \"sss\": unsupported protocol scheme \"\"","res":"Get \"sss\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-17T11:37:31+07:00"}
{"err":"Get \"sss\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"sss\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"sss","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-17T11:37:31+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-18T12:05:52+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-18T12:05:52+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-18T12:06:00+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-18T12:06:00+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-18T12:59:41+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":296,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-18T12:59:41+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T16:59:42+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T16:59:42+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:02:22+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:02:24+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:02:24+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:01+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:01+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:12+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:12+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:18+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:18+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:49+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:51+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T17:03:51+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T20:31:36+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T20:31:36+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T20:31:58+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T20:32:33+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T20:32:35+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable host.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T20:32:38+07:00"}
{"level":"error","msg":"Get \"https://crmconnect.misa.vn/api/v1/Customers\": read tcp 192.168.0.102:59747-\u003e103.53.89.24:443: wsarecv: An existing connection was forcibly closed by the remote host.","res":"Get \"https://crmconnect.misa.vn/api/v1/Customers\": read tcp 192.168.0.102:59747-\u003e103.53.89.24:443: wsarecv: An existing connection was forcibly closed by the remote host.","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-18T21:48:12+07:00"}
{"err":"Get \"https://crmconnect.misa.vn/api/v1/Customers\": read tcp 192.168.0.102:59747-\u003e103.53.89.24:443: wsarecv: An existing connection was forcibly closed by the remote host.","level":"error","msg":"Get \"https://crmconnect.misa.vn/api/v1/Customers\": read tcp 192.168.0.102:59747-\u003e103.53.89.24:443: wsarecv: An existing connection was forcibly closed by the remote host.","req":{"Header":{},"Body":{},"Url":"https://crmconnect.misa.vn/api/v1/Customers","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-18T21:48:12+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable network.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T23:40:26+07:00"}
{"level":"error","msg":"dial tcp 14.225.0.166:5432: connectex: A socket operation was attempted to an unreachable network.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-18T23:40:26+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T01:23:16+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{"asdasd":"wwwqq"},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T01:23:17+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T13:36:05+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T13:36:05+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T14:23:43+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{"Authorization":"Misa token"},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T14:23:43+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T14:25:25+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{"Authorization":"Misa token"},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T14:25:25+07:00"}
{"level":"error","msg":"Get \"2222\": unsupported protocol scheme \"\"","res":"Get \"2222\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T14:25:45+07:00"}
{"err":"Get \"2222\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"2222\": unsupported protocol scheme \"\"","req":{"Header":{"Authorization":"Misa token"},"Body":{},"Url":"2222","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T14:25:45+07:00"}
{"level":"error","msg":"Get \"2222\": unsupported protocol scheme \"\"","res":"Get \"2222\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T14:25:50+07:00"}
{"err":"Get \"2222\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"2222\": unsupported protocol scheme \"\"","req":{"Header":{"Authorization":"Misa token"},"Body":{},"Url":"2222","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T14:25:50+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T14:31:23+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T14:31:23+07:00"}
{"level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","res":"Get \"\": unsupported protocol scheme \"\"","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-01-19T14:31:27+07:00"}
{"err":"Get \"\": unsupported protocol scheme \"\"","level":"error","msg":"Get \"\": unsupported protocol scheme \"\"","req":{"Header":{},"Body":{},"Url":"","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":297,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-01-19T14:31:27+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-31T14:43:17+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-01-31T14:43:21+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:29:21+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:29:21+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:39:33+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:39:33+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:41:33+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:41:34+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:43:58+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:43:58+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:44:15+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:44:15+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:45:19+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:45:19+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:45:56+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:45:56+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:55:25+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:56:07+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:56:55+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:57:37+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:8080: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:59:50+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:8080: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:59:50+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:8080: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:59:54+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:8080: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T09:59:54+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:01:25+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:02:07+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:03:01+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:03:43+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:05:02+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:05:44+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:07:24+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:08:06+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:08:32+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:09:14+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:09:32+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:09:32+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:09:42+07:00"}
{"level":"error","msg":"dial tcp: lookup 14.255.0.166:: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:09:42+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:12:29+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:13:11+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:13:57+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:14:39+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:17:32+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:17:49+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:17:56+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:18:31+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:18:38+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:21:56+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:22:38+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:24:34+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:25:14+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:25:16+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:25:56+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:27:00+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:27:42+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":35,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:34:04+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":35,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:34:46+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":35,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:35:31+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":35,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:36:13+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":35,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:36:59+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:37:44+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:38:26+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:39:13+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:39:55+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:42:46+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:43:28+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:44:16+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:44:58+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:46:40+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:47:22+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:49:04+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:49:46+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:50:36+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:51:18+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:54:36+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":36,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:55:18+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:58:08+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:58:50+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T10:59:40+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:00:22+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:02:26+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:03:08+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:04:00+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":38,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:04:43+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:06:10+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:06:53+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:08:31+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:09:13+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:10:55+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:11:37+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:13:26+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:14:08+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:14:55+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":39,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:15:38+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":41,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:17:22+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":41,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:18:04+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":41,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:18:51+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":41,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:19:33+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":41,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:21:03+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":41,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:21:45+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":41,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T11:23:27+07:00"}
{"level":"error","msg":"Get \"https://%C3%A1d%E1%BA%A5ds\": dial tcp: lookup xn--dds-dla5129a: no such host","res":"Get \"https://%C3%A1d%E1%BA%A5ds\": dial tcp: lookup xn--dds-dla5129a: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/library/Request.go","Line":63,"Func":"data-connector/library.Request.Send"},"time":"2023-02-01T11:57:27+07:00"}
{"err":"Get \"https://%C3%A1d%E1%BA%A5ds\": dial tcp: lookup xn--dds-dla5129a: no such host","level":"error","msg":"Get \"https://%C3%A1d%E1%BA%A5ds\": dial tcp: lookup xn--dds-dla5129a: no such host","req":{"Header":{},"Body":{},"Url":"https://ádấds","Method":"","SuppressParseData":true},"scope":{"File":"D:/work space/data-connector.symper.vn/model/ApiQuery.go","Line":303,"Func":"data-connector/model.ApiQuery.ExtractData"},"time":"2023-02-01T11:57:27+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:31:02+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:31:44+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:34:10+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:34:52+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:35:56+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:36:38+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:38:30+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":43,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-01T13:39:12+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:33:52+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:33:52+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:40:18+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:40:19+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:50:31+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:51:10+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:51:11+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:54:56+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:54:57+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:55:00+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T09:55:00+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:04:05+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:04:47+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:07:23+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:08:38+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:08:39+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:08:43+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:08:43+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:08:46+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:08:47+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:09:52+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:09:52+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:09:57+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:09:58+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:10:24+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:10:29+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:10:37+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:10:46+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:10:56+07:00"}
{"level":"error","msg":"dial tcp: lookup postgres: no such host","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:11:06+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:11:48+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:11:48+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:11:53+07:00"}
{"level":"error","msg":"pq: password authentication failed for user \"dev\"","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:11:54+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:13:01+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:13:43+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:16:32+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:17:14+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:25:43+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:25:55+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:26:03+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T10:26:37+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T11:43:30+07:00"}
{"level":"error","msg":"dial tcp 14.255.0.166:5432: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T11:44:13+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.91.217\", user \"data_connector\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T13:59:30+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.91.217\", user \"data_connector\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T13:59:30+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.91.217\", user \"data_connector\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T14:15:04+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.91.217\", user \"data_connector\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T14:15:10+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.91.217\", user \"data_connector\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T14:15:10+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.91.217\", user \"data_connector\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T14:16:24+07:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"58.186.91.217\", user \"data_connector\", database \"data_connector_symper_vn\", SSL off","scope":{"File":"D:/work space/data-connector.symper.vn/model/Connection.go","Line":34,"Func":"data-connector/model.ConnectSql"},"time":"2023-02-02T14:16:24+07:00"}
